baseURL = "https://nikibobi.github.io/"
languageCode = "en-us"
title = "Borislav Kosharov"
subtitle = "Thoughts on programming and math"
theme = "terminal"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

[languages]
  [languages.en]
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "kosharov.ml"
      logoHomeLink = "/posts"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
