baseURL = "https://nikibobi.github.io/"
languageCode = "en-US"
title = "kosharov.ml"
subtitle = "Thoughts on programming and math"
theme = "cocoa-eh"

[params]
  dateform = "Jan 2, 2006"
  dateformfull = "Mon Jan 2 2006 15:04:05 MST"
  description = "Thoughts on programming and math"
  logofile = "img/logo.jpeg"
  faviconfile = ""
  highlightjs = true
  progressively = true
  uselatex = true
  github = "nikibobi"
  email = "bosakmaw@gmail.com"
  linkedin = "borislav-kosharov-455b59163"
  twitter = "bosakmaw"
  social_banner = "img/banner.png"
  posts_navigation = true
  small_banner_logo = true
